receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
    
  # problem here : not able to connect it with jaeger
  # otlp/jaeger:
  #   endpoint: jaeger-server:4317

exporters:
  debug:
    verbosity: detailed
  # otlp:
  #   endpoint: otelcol:4317

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
      # exporters: [debug, otlp/jaeger]
    metrics:
      receivers: [otlp]
      exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug]
